spring:
  datasource:
    username: root
    password: 2876650126
    url: jdbc:mysql://localhost:3306/zhangheng
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      cache=false:
  mail:
    host: smtp.qq.com
    username: 2876650126@qq.com
    password: ylffmpgtwavydccb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: com.example.springbootmybatis.pojo
  mapper-locations: classpath:mybatis/*.xml
server:
  port: 8080
